<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;
use App\Models\ProductCategory;
use App\Models\ProductImage;

class ProductSeeder extends Seeder
{
    public function run()
    {
        $products = [
            [
                'name' => 'Breakfast',
                'variant' => 'Light',
                'description' => 'Delicious light roast from our blends selection.',
                'price' => 18.99,
                'weight' => 250,
                'stock' => 100,
                'category' => 'Blends',
                'images' => [
                    'products/blends/breakfast_light_250.jpg',
                    'categories/category_blends.jpg',
                ],
            ],
            [
                'name' => 'Breakfast',
                'variant' => 'Light',
                'description' => 'Delicious light roast from our blends selection.',
                'price' => 29.99,
                'weight' => 500,
                'stock' => 60,
                'category' => 'Blends',
                'images' => [
                    'products/blends/breakfast_light_500.jpg',
                    'categories/category_blends.jpg',
                ],
            ],
            [
                'name' => 'Breakfast',
                'variant' => 'Medium',
                'description' => 'Delicious medium roast from our blends selection.',
                'price' => 18.99,
                'weight' => 250,
                'stock' => 100,
                'category' => 'Blends',
                'images' => [
                    'products/blends/breakfast_medium_250.jpg',
                    'categories/category_blends.jpg',
                ],
            ],
            [
                'name' => 'Breakfast',
                'variant' => 'Medium',
                'description' => 'Delicious medium roast from our blends selection.',
                'price' => 29.99,
                'weight' => 500,
                'stock' => 60,
                'category' => 'Blends',
                'images' => [
                    'products/blends/breakfast_medium_500.jpg',
                    'categories/category_blends.jpg',
                ],
            ],
            [
                'name' => 'Espresso',
                'variant' => 'Dark',
                'description' => 'Delicious dark roast from our blends selection.',
                'price' => 18.99,
                'weight' => 250,
                'stock' => 100,
                'category' => 'Blends',
                'images' => [
                    'products/blends/espresso_dark_250.jpg',
                    'categories/category_blends.jpg',
                ],
            ],
            [
                'name' => 'Espresso',
                'variant' => 'Dark',
                'description' => 'Delicious dark roast from our blends selection.',
                'price' => 29.99,
                'weight' => 500,
                'stock' => 60,
                'category' => 'Blends',
                'images' => [
                    'products/blends/espresso_dark_500.jpg',
                    'categories/category_blends.jpg',
                ],
            ],
            [
                'name' => 'Espresso',
                'variant' => 'Medium',
                'description' => 'Delicious medium roast from our blends selection.',
                'price' => 18.99,
                'weight' => 250,
                'stock' => 100,
                'category' => 'Blends',
                'images' => [
                    'products/blends/espresso_medium_250.jpg',
                    'categories/category_blends.jpg',
                ],
            ],
            [
                'name' => 'Espresso',
                'variant' => 'Medium',
                'description' => 'Delicious medium roast from our blends selection.',
                'price' => 29.99,
                'weight' => 500,
                'stock' => 60,
                'category' => 'Blends',
                'images' => [
                    'products/blends/espresso_medium_500.jpg',
                    'categories/category_blends.jpg',
                ],
            ],
            [
                'name' => 'House',
                'variant' => 'Light',
                'description' => 'Delicious light roast from our blends selection.',
                'price' => 18.99,
                'weight' => 250,
                'stock' => 100,
                'category' => 'Blends',
                'images' => [
                    'products/blends/house_light_250.jpg',
                    'categories/category_blends.jpg',
                ],
            ],
            [
                'name' => 'House',
                'variant' => 'Light',
                'description' => 'Delicious light roast from our blends selection.',
                'price' => 29.99,
                'weight' => 500,
                'stock' => 60,
                'category' => 'Blends',
                'images' => [
                    'products/blends/house_light_500.jpg',
                    'categories/category_blends.jpg',
                ],
            ],
            [
                'name' => 'House',
                'variant' => 'Medium',
                'description' => 'Delicious medium roast from our blends selection.',
                'price' => 18.99,
                'weight' => 250,
                'stock' => 100,
                'category' => 'Blends',
                'images' => [
                    'products/blends/house_medium_250.jpg',
                    'categories/category_blends.jpg',
                ],
            ],
            [
                'name' => 'House',
                'variant' => 'Medium',
                'description' => 'Delicious medium roast from our blends selection.',
                'price' => 29.99,
                'weight' => 500,
                'stock' => 60,
                'category' => 'Blends',
                'images' => [
                    'products/blends/house_medium_500.jpg',
                    'categories/category_blends.jpg',
                ],
            ],
            [
                'name' => 'Italian',
                'variant' => 'Dark',
                'description' => 'Delicious dark roast from our blends selection.',
                'price' => 18.99,
                'weight' => 250,
                'stock' => 100,
                'category' => 'Blends',
                'images' => [
                    'products/blends/italian_dark_250.jpg',
                    'categories/category_blends.jpg',
                ],
            ],
            [
                'name' => 'Italian',
                'variant' => 'Dark',
                'description' => 'Delicious dark roast from our blends selection.',
                'price' => 29.99,
                'weight' => 500,
                'stock' => 60,
                'category' => 'Blends',
                'images' => [
                    'products/blends/italian_dark_500.jpg',
                    'categories/category_blends.jpg',
                ],
            ],
            [
                'name' => 'Mocha',
                'variant' => 'Medium',
                'description' => 'Delicious medium roast from our blends selection.',
                'price' => 18.99,
                'weight' => 250,
                'stock' => 100,
                'category' => 'Blends',
                'images' => [
                    'products/blends/mocha_medium_250.jpg',
                    'categories/category_blends.jpg',
                ],
            ],
            [
                'name' => 'Mocha',
                'variant' => 'Medium',
                'description' => 'Delicious medium roast from our blends selection.',
                'price' => 29.99,
                'weight' => 500,
                'stock' => 60,
                'category' => 'Blends',
                'images' => [
                    'products/blends/mocha_medium_500.jpg',
                    'categories/category_blends.jpg',
                ],
            ],
            [
                'name' => 'Coldbrew',
                'variant' => 'Medium',
                'description' => 'Delicious medium roast from our decaf specials selection.',
                'price' => 18.99,
                'weight' => 250,
                'stock' => 100,
                'category' => 'Decaf Specials',
                'images' => [
                    'products/decaf-specials/coldbrew_medium_250.jpg',
                    'categories/category_specials.jpg',
                ],
            ],
            [
                'name' => 'Coldbrew',
                'variant' => 'Medium',
                'description' => 'Delicious medium roast from our decaf specials selection.',
                'price' => 29.99,
                'weight' => 500,
                'stock' => 60,
                'category' => 'Decaf Specials',
                'images' => [
                    'products/decaf-specials/coldbrew_medium_500.jpg',
                    'categories/category_specials.jpg',
                ],
            ],
            [
                'name' => 'Decafcolombia',
                'variant' => 'Dark',
                'description' => 'Delicious dark roast from our decaf specials selection.',
                'price' => 18.99,
                'weight' => 250,
                'stock' => 100,
                'category' => 'Decaf Specials',
                'images' => [
                    'products/decaf-specials/decafcolombia_dark_250.jpg',
                    'categories/category_specials.jpg',
                ],
            ],
            [
                'name' => 'Decafcolombia',
                'variant' => 'Dark',
                'description' => 'Delicious dark roast from our decaf specials selection.',
                'price' => 29.99,
                'weight' => 500,
                'stock' => 60,
                'category' => 'Decaf Specials',
                'images' => [
                    'products/decaf-specials/decafcolombia_dark_500.jpg',
                    'categories/category_specials.jpg',
                ],
            ],
            [
                'name' => 'Decafcolombia',
                'variant' => 'Medium',
                'description' => 'Delicious medium roast from our decaf specials selection.',
                'price' => 18.99,
                'weight' => 250,
                'stock' => 100,
                'category' => 'Decaf Specials',
                'images' => [
                    'products/decaf-specials/decafcolombia_medium_250.jpg',
                    'categories/category_specials.jpg',
                ],
            ],
            [
                'name' => 'Decafcolombia',
                'variant' => 'Medium',
                'description' => 'Delicious medium roast from our decaf specials selection.',
                'price' => 29.99,
                'weight' => 500,
                'stock' => 60,
                'category' => 'Decaf Specials',
                'images' => [
                    'products/decaf-specials/decafcolombia_medium_500.jpg',
                    'categories/category_specials.jpg',
                ],
            ],
            [
                'name' => 'Decafespresso',
                'variant' => 'Dark',
                'description' => 'Delicious dark roast from our decaf specials selection.',
                'price' => 18.99,
                'weight' => 250,
                'stock' => 100,
                'category' => 'Decaf Specials',
                'images' => [
                    'products/decaf-specials/decafespresso_dark_250.jpg',
                    'categories/category_specials.jpg',
                ],
            ],
            [
                'name' => 'Decafespresso',
                'variant' => 'Dark',
                'description' => 'Delicious dark roast from our decaf specials selection.',
                'price' => 29.99,
                'weight' => 500,
                'stock' => 60,
                'category' => 'Decaf Specials',
                'images' => [
                    'products/decaf-specials/decafespresso_dark_500.jpg',
                    'categories/category_specials.jpg',
                ],
            ],
            [
                'name' => 'Gentleroast',
                'variant' => 'Light',
                'description' => 'Delicious light roast from our decaf specials selection.',
                'price' => 18.99,
                'weight' => 250,
                'stock' => 100,
                'category' => 'Decaf Specials',
                'images' => [
                    'products/decaf-specials/gentleroast_light_250.jpg',
                    'categories/category_specials.jpg',
                ],
            ],
            [
                'name' => 'Gentleroast',
                'variant' => 'Light',
                'description' => 'Delicious light roast from our decaf specials selection.',
                'price' => 29.99,
                'weight' => 500,
                'stock' => 60,
                'category' => 'Decaf Specials',
                'images' => [
                    'products/decaf-specials/gentleroast_light_500.jpg',
                    'categories/category_specials.jpg',
                ],
            ],
            [
                'name' => 'Milklovers',
                'variant' => 'Medium',
                'description' => 'Delicious medium roast from our decaf specials selection.',
                'price' => 18.99,
                'weight' => 250,
                'stock' => 100,
                'category' => 'Decaf Specials',
                'images' => [
                    'products/decaf-specials/milklovers_medium_250.jpg',
                    'categories/category_specials.jpg',
                ],
            ],
            [
                'name' => 'Milklovers',
                'variant' => 'Medium',
                'description' => 'Delicious medium roast from our decaf specials selection.',
                'price' => 29.99,
                'weight' => 500,
                'stock' => 60,
                'category' => 'Decaf Specials',
                'images' => [
                    'products/decaf-specials/milklovers_medium_500.jpg',
                    'categories/category_specials.jpg',
                ],
            ],
            [
                'name' => 'Swissdecaf',
                'variant' => 'Medium',
                'description' => 'Delicious medium roast from our decaf specials selection.',
                'price' => 18.99,
                'weight' => 250,
                'stock' => 100,
                'category' => 'Decaf Specials',
                'images' => [
                    'products/decaf-specials/swissdecaf_medium_250.jpg',
                    'categories/category_specials.jpg',
                ],
            ],
            [
                'name' => 'Swissdecaf',
                'variant' => 'Medium',
                'description' => 'Delicious medium roast from our decaf specials selection.',
                'price' => 29.99,
                'weight' => 500,
                'stock' => 60,
                'category' => 'Decaf Specials',
                'images' => [
                    'products/decaf-specials/swissdecaf_medium_500.jpg',
                    'categories/category_specials.jpg',
                ],
            ],
            [
                'name' => 'Elsalvador',
                'variant' => 'Medium',
                'description' => 'Delicious medium roast from our limited edition selection.',
                'price' => 18.99,
                'weight' => 250,
                'stock' => 100,
                'category' => 'Limited Edition',
                'images' => [
                    'products/limited-edition/elsalvador_medium_250.jpg',
                    'categories/category_limited.jpg',
                ],
            ],
            [
                'name' => 'Elsalvador',
                'variant' => 'Medium',
                'description' => 'Delicious medium roast from our limited edition selection.',
                'price' => 29.99,
                'weight' => 500,
                'stock' => 60,
                'category' => 'Limited Edition',
                'images' => [
                    'products/limited-edition/elsalvador_medium_500.jpg',
                    'categories/category_limited.jpg',
                ],
            ],
            [
                'name' => 'Geisha',
                'variant' => 'Dark',
                'description' => 'Delicious dark roast from our limited edition selection.',
                'price' => 18.99,
                'weight' => 250,
                'stock' => 100,
                'category' => 'Limited Edition',
                'images' => [
                    'products/limited-edition/geisha_dark_250.jpg',
                    'categories/category_limited.jpg',
                ],
            ],
            [
                'name' => 'Geisha',
                'variant' => 'Dark',
                'description' => 'Delicious dark roast from our limited edition selection.',
                'price' => 29.99,
                'weight' => 500,
                'stock' => 60,
                'category' => 'Limited Edition',
                'images' => [
                    'products/limited-edition/geisha_dark_500.jpg',
                    'categories/category_limited.jpg',
                ],
            ],
            [
                'name' => 'Geisha',
                'variant' => 'Medium',
                'description' => 'Delicious medium roast from our limited edition selection.',
                'price' => 18.99,
                'weight' => 250,
                'stock' => 100,
                'category' => 'Limited Edition',
                'images' => [
                    'products/limited-edition/geisha_medium_250.jpg',
                    'categories/category_limited.jpg',
                ],
            ],
            [
                'name' => 'Geisha',
                'variant' => 'Medium',
                'description' => 'Delicious medium roast from our limited edition selection.',
                'price' => 29.99,
                'weight' => 500,
                'stock' => 60,
                'category' => 'Limited Edition',
                'images' => [
                    'products/limited-edition/geisha_medium_500.jpg',
                    'categories/category_limited.jpg',
                ],
            ],
            [
                'name' => 'Honduras',
                'variant' => 'Dark',
                'description' => 'Delicious dark roast from our limited edition selection.',
                'price' => 18.99,
                'weight' => 250,
                'stock' => 100,
                'category' => 'Limited Edition',
                'images' => [
                    'products/limited-edition/honduras_dark_250.jpg',
                    'categories/category_limited.jpg',
                ],
            ],
            [
                'name' => 'Honduras',
                'variant' => 'Dark',
                'description' => 'Delicious dark roast from our limited edition selection.',
                'price' => 29.99,
                'weight' => 500,
                'stock' => 60,
                'category' => 'Limited Edition',
                'images' => [
                    'products/limited-edition/honduras_dark_500.jpg',
                    'categories/category_limited.jpg',
                ],
            ],
            [
                'name' => 'Yemen',
                'variant' => 'Medium',
                'description' => 'Delicious medium roast from our limited edition selection.',
                'price' => 18.99,
                'weight' => 250,
                'stock' => 100,
                'category' => 'Limited Edition',
                'images' => [
                    'products/limited-edition/yemen_medium_250.jpg',
                    'categories/category_limited.jpg',
                ],
            ],
            [
                'name' => 'Yemen',
                'variant' => 'Medium',
                'description' => 'Delicious medium roast from our limited edition selection.',
                'price' => 29.99,
                'weight' => 500,
                'stock' => 60,
                'category' => 'Limited Edition',
                'images' => [
                    'products/limited-edition/yemen_medium_500.jpg',
                    'categories/category_limited.jpg',
                ],
            ],
            [
                'name' => 'Brazil',
                'variant' => 'Dark',
                'description' => 'Delicious dark roast from our single origin selection.',
                'price' => 18.99,
                'weight' => 250,
                'stock' => 100,
                'category' => 'Single Origin',
                'images' => [
                    'products/single-origin/brazil_dark_250.jpg',
                    'categories/category_singleorigin.jpg',
                ],
            ],
            [
                'name' => 'Brazil',
                'variant' => 'Dark',
                'description' => 'Delicious dark roast from our single origin selection.',
                'price' => 29.99,
                'weight' => 500,
                'stock' => 60,
                'category' => 'Single Origin',
                'images' => [
                    'products/single-origin/brazil_dark_500.jpg',
                    'categories/category_singleorigin.jpg',
                ],
            ],
            [
                'name' => 'Brazil',
                'variant' => 'Medium',
                'description' => 'Delicious medium roast from our single origin selection.',
                'price' => 18.99,
                'weight' => 250,
                'stock' => 100,
                'category' => 'Single Origin',
                'images' => [
                    'products/single-origin/brazil_medium_250.jpg',
                    'categories/category_singleorigin.jpg',
                ],
            ],
            [
                'name' => 'Brazil',
                'variant' => 'Medium',
                'description' => 'Delicious medium roast from our single origin selection.',
                'price' => 29.99,
                'weight' => 500,
                'stock' => 60,
                'category' => 'Single Origin',
                'images' => [
                    'products/single-origin/brazil_medium_500.jpg',
                    'categories/category_singleorigin.jpg',
                ],
            ],
            [
                'name' => 'Colombia',
                'variant' => 'Dark',
                'description' => 'Delicious dark roast from our single origin selection.',
                'price' => 18.99,
                'weight' => 250,
                'stock' => 100,
                'category' => 'Single Origin',
                'images' => [
                    'products/single-origin/colombia_dark_250.jpg',
                    'categories/category_singleorigin.jpg',
                ],
            ],
            [
                'name' => 'Colombia',
                'variant' => 'Dark',
                'description' => 'Delicious dark roast from our single origin selection.',
                'price' => 29.99,
                'weight' => 500,
                'stock' => 60,
                'category' => 'Single Origin',
                'images' => [
                    'products/single-origin/colombia_dark_500.jpg',
                    'categories/category_singleorigin.jpg',
                ],
            ],
            [
                'name' => 'Colombia',
                'variant' => 'Medium',
                'description' => 'Delicious medium roast from our single origin selection.',
                'price' => 18.99,
                'weight' => 250,
                'stock' => 100,
                'category' => 'Single Origin',
                'images' => [
                    'products/single-origin/colombia_medium_250.jpg',
                    'categories/category_singleorigin.jpg',
                ],
            ],
            [
                'name' => 'Colombia',
                'variant' => 'Medium',
                'description' => 'Delicious medium roast from our single origin selection.',
                'price' => 29.99,
                'weight' => 500,
                'stock' => 60,
                'category' => 'Single Origin',
                'images' => [
                    'products/single-origin/colombia_medium_500.jpg',
                    'categories/category_singleorigin.jpg',
                ],
            ],
            [
                'name' => 'Ethiopia',
                'variant' => 'Dark',
                'description' => 'Delicious dark roast from our single origin selection.',
                'price' => 18.99,
                'weight' => 250,
                'stock' => 100,
                'category' => 'Single Origin',
                'images' => [
                    'products/single-origin/ethiopia_dark_250.jpg',
                    'categories/category_singleorigin.jpg',
                ],
            ],
            [
                'name' => 'Ethiopia',
                'variant' => 'Dark',
                'description' => 'Delicious dark roast from our single origin selection.',
                'price' => 29.99,
                'weight' => 500,
                'stock' => 60,
                'category' => 'Single Origin',
                'images' => [
                    'products/single-origin/ethiopia_dark_500.jpg',
                    'categories/category_singleorigin.jpg',
                ],
            ],
            [
                'name' => 'Ethiopia',
                'variant' => 'Medium',
                'description' => 'Delicious medium roast from our single origin selection.',
                'price' => 18.99,
                'weight' => 250,
                'stock' => 100,
                'category' => 'Single Origin',
                'images' => [
                    'products/single-origin/ethiopia_medium_250.jpg',
                    'categories/category_singleorigin.jpg',
                ],
            ],
            [
                'name' => 'Ethiopia',
                'variant' => 'Medium',
                'description' => 'Delicious medium roast from our single origin selection.',
                'price' => 29.99,
                'weight' => 500,
                'stock' => 60,
                'category' => 'Single Origin',
                'images' => [
                    'products/single-origin/ethiopia_medium_500.jpg',
                    'categories/category_singleorigin.jpg',
                ],
            ],
            [
                'name' => 'Guatemala',
                'variant' => 'Dark',
                'description' => 'Delicious dark roast from our single origin selection.',
                'price' => 18.99,
                'weight' => 250,
                'stock' => 100,
                'category' => 'Single Origin',
                'images' => [
                    'products/single-origin/guatemala_dark_250.jpg',
                    'categories/category_singleorigin.jpg',
                ],
            ],
            [
                'name' => 'Guatemala',
                'variant' => 'Dark',
                'description' => 'Delicious dark roast from our single origin selection.',
                'price' => 29.99,
                'weight' => 500,
                'stock' => 60,
                'category' => 'Single Origin',
                'images' => [
                    'products/single-origin/guatemala_dark_500.jpg',
                    'categories/category_singleorigin.jpg',
                ],
            ],
            [
                'name' => 'Guatemala',
                'variant' => 'Medium',
                'description' => 'Delicious medium roast from our single origin selection.',
                'price' => 18.99,
                'weight' => 250,
                'stock' => 100,
                'category' => 'Single Origin',
                'images' => [
                    'products/single-origin/guatemala_medium_250.jpg',
                    'categories/category_singleorigin.jpg',
                ],
            ],
            [
                'name' => 'Guatemala',
                'variant' => 'Medium',
                'description' => 'Delicious medium roast from our single origin selection.',
                'price' => 29.99,
                'weight' => 500,
                'stock' => 60,
                'category' => 'Single Origin',
                'images' => [
                    'products/single-origin/guatemala_medium_500.jpg',
                    'categories/category_singleorigin.jpg',
                ],
            ],
        ];

        foreach ($products as $data) {
            $category = ProductCategory::where('name', $data['category'])->first();
            $product = Product::create([
                'name' => $data['name'],
                'variant' => $data['variant'],
                'description' => $data['description'],
                'price' => $data['price'],
                'weight' => $data['weight'],
                'stock' => $data['stock'],
                'product_category_id' => $category->id,
            ]);

            foreach ($data['images'] as $image) {
                ProductImage::create([
                    'product_id' => $product->id,
                    'image_path' => $image,
                ]);
            }
        }
    }
}
